name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:     
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd src && ./configure
    - name: make
      run: cd src && make
    - name: make check
      run: cd src && make check
    - name: make distcheck
      run: cd src && make distcheck
